import { Kamar, Mahasantri, SKMahasantri } from './types';

export const SK_INFO = {
  nomor: 'B-092/Un.30/P.IV/KP.07.06/06/2026',
  judul: 'PENETAPAN NAMA-NAMA DAN JADWAL CEK IN MAHASANTRI BARU PROGRAM MUKIM GELOMBANG 1 T.A. 2026/2027',
  instansi: 'UPT MA\'HAD AL-JAMI\'AH UIN SIBER SYEKH NURJATI CIREBON',
  jadwal: '19 - 21 Agustus 2026 (Pukul 08.00 – 16.00 WIB)',
  contactPerson: '0858-6275-9619',
  mudir: 'Dr. Muhsin Riyadi, MA',
  lokasiPutra: 'Asrama Ma\'had Qodim',
  lokasiPutri: 'Asrama Ma\'had Jadid',
};

// Generate default rooms for Ma'had Qodim (Putra) - Lantai 1 to 5
export function generateInitialRooms(): Kamar[] {
  const rooms: Kamar[] = [];
  const floors = [1, 2, 3, 4, 5];

  floors.forEach((floor) => {
    // Jajaran Depan: 4 kamar (09 - 12)
    for (let i = 9; i <= 12; i++) {
      const roomNum = `${floor}${i < 10 ? '0' + i : i}`;
      const isLantai2 = floor === 2; // Lantai 2 is International by default
      rooms.push({
        id: `K-${roomNum}`,
        nomor: roomNum,
        lantai: floor,
        jajaran: 'DEPAN',
        gedung: "Ma'had Qodim",
        gender: 'L',
        kategori: isLantai2 ? 'INTERNASIONAL' : 'UMUM',
        isLocked: isLantai2,
        lockReason: isLantai2 ? 'Khusus Mahasantri Internasional' : undefined,
        kapasitas: 4,
        beds: [
          { bedNumber: 1, isOccupied: false },
          { bedNumber: 2, isOccupied: false },
          { bedNumber: 3, isOccupied: false },
          { bedNumber: 4, isOccupied: false },
        ],
      });
    }

    // Jajaran Belakang: 4 kamar (13 - 16)
    for (let i = 13; i <= 16; i++) {
      const roomNum = `${floor}${i}`;
      const isLantai2 = floor === 2;
      rooms.push({
        id: `K-${roomNum}`,
        nomor: roomNum,
        lantai: floor,
        jajaran: 'BELAKANG',
        gedung: "Ma'had Qodim",
        gender: 'L',
        kategori: isLantai2 ? 'INTERNASIONAL' : 'UMUM',
        isLocked: isLantai2,
        lockReason: isLantai2 ? 'Khusus Mahasantri Internasional' : undefined,
        kapasitas: 4,
        beds: [
          { bedNumber: 1, isOccupied: false },
          { bedNumber: 2, isOccupied: false },
          { bedNumber: 3, isOccupied: false },
          { bedNumber: 4, isOccupied: false },
        ],
      });
    }
  });

  return rooms;
}

// Master Data SK Resmi dari Dokumen Pengumuman Mahad No. B-092/Un.30/P.IV/KP.07.06/06/2026
export const INITIAL_SK_LIST: SKMahasantri[] = [
  // --- MAHASANTRI PUTRA (CALON MAHASANTRI BARU BERBASIS NISN & PERPANJANGAN BERBASIS NIM) ---
  {
    no: 4,
    nimNisn: '0067999651',
    nama: 'Abdullah Al Mu\'izi Mafas',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FASYA',
    jurusan: 'HUKUM KELUARGA ISLAM',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 5,
    nimNisn: '0074324633',
    nama: 'Abdullah Fasya',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'PAI',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 6,
    nimNisn: '0081064205',
    nama: 'Abdullah ma\'ruf',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'MPI',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 7,
    nimNisn: '0081139935',
    nama: 'Achmad Labib ’Afify',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'PIAUD',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 8,
    nimNisn: '0094524939',
    nama: 'Achmad Maher sirojulkaf',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FEBI',
    jurusan: 'BIOTEKNOLOGI',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 9,
    nimNisn: '0076281399',
    nama: 'ADAM ALFI WAHDA',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'TADRIS B. INGGRIS',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 10,
    nimNisn: '0074173366',
    nama: 'Adam Mansur',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FASYA',
    jurusan: 'HUKUM TATANEGARA',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 15,
    nimNisn: '0073338690',
    nama: 'Aditya',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'PAI',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 16,
    nimNisn: '0089221715',
    nama: 'Adli Ramadhani',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FDKI',
    jurusan: 'KOMUNIKASI PENYIARAN ISLAM',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 18,
    nimNisn: '0077252088',
    nama: 'Affan Nurali Hasan',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FDKI',
    jurusan: 'KOMUNIKASI PENYIARAN ISLAM',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 19,
    nimNisn: '0088131041',
    nama: 'Afif Fayyadh Ramadhan',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FASYA',
    jurusan: 'HUKUM KELUARGA ISLAM',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 28,
    nimNisn: '2530414009',
    nama: 'Ahmad Ardhi Hasan',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Perpanjangan',
    fakultas: 'FDKI',
    jurusan: 'SOSIOLOGI AGAMA',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 31,
    nimNisn: '2530801078',
    nama: 'Ahmad Zaky Rahul',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Perpanjangan',
    fakultas: 'FITK',
    jurusan: 'INFORMATIKA',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 719,
    nimNisn: '2530311086',
    nama: 'SUFYAN TSAURY',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Perpanjangan',
    fakultas: 'FASYA',
    jurusan: 'HUKUM KELUARGA ISLAM',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 742,
    nimNisn: '2530801002',
    nama: 'TAUFIK ARROKHMAN',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Perpanjangan',
    fakultas: 'FITK',
    jurusan: 'INFORMATIKA',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },

  // --- MAHASANTRI INTERNASIONAL DARI SK RESMI (HALAMAN 33 - 35) ---
  {
    no: 846,
    nimNisn: 'INT-PH-846',
    nama: 'Aleanor L. Sharif',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Filipina',
    fakultas: 'FITK',
    jurusan: 'PAI',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 847,
    nimNisn: 'INT-PH-847',
    nama: 'Prince Adzhar Salisipan Duran',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Filipina',
    fakultas: 'FITK',
    jurusan: 'PAI',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 849,
    nimNisn: 'INT-TH-849',
    nama: 'Adam Saraeh',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Thailand',
    fakultas: 'FUA',
    jurusan: 'Ilmu Al-Qur\'an & Tafsir (IAT)',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 853,
    nimNisn: 'INT-SD-853',
    nama: 'Khaled Eltayeb Abdalla Fagdalla',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Sudan',
    fakultas: 'FUA',
    jurusan: 'Tasawuf & Psikoterapi (TAPSI)',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 863,
    nimNisn: 'INT-NG-863',
    nama: 'Muhammad Bello Abbas',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Nigeria',
    fakultas: 'FEBI',
    jurusan: 'Akuntansi Syariah (AKSYAR)',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 868,
    nimNisn: 'INT-PK-868',
    nama: 'Aadil Ali',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Pakistan',
    fakultas: 'FITK',
    jurusan: 'Tadris Bahasa Indonesia',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 873,
    nimNisn: 'INT-EG-873',
    nama: 'Mohamed Khaled Hassan',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Mesir (Egypt)',
    fakultas: 'FITK',
    jurusan: 'Pendidikan Bahasa Arab (PBA)',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 875,
    nimNisn: 'INT-YE-875',
    nama: 'Mohammed Ali Mohammed Abdulwahid Rageh',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Yaman',
    fakultas: 'FDKI',
    jurusan: 'Pengembangan Masyarakat Islam (PMI)',
    isInternasional: true,
    skNomor: SK_INFO.nomor,
  },

  // --- MAHASANTRI PUTRI (CONTOH DARI SK) ---
  {
    no: 1,
    nimNisn: '0082269226',
    nama: 'Aah Nurhasanah',
    jenisKelamin: 'P',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'TADRIS B. INDONESIA',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 2,
    nimNisn: '0086571930',
    nama: 'Aas Asyipatul Hodijah',
    jenisKelamin: 'P',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FITK',
    jurusan: 'PBA',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
  {
    no: 12,
    nimNisn: '2530411130',
    nama: 'Adinda Khoirun Nisa',
    jenisKelamin: 'P',
    jenisPendaftaran: 'Perpanjangan',
    fakultas: 'FDKI',
    jurusan: 'KOMUNIKASI PENYIARAN ISLAM',
    isInternasional: false,
    skNomor: SK_INFO.nomor,
  },
];

// Initial pre-booked Mahasantri
export const INITIAL_MAHASANTRI: Mahasantri[] = [
  {
    id: 'MHS-001',
    nimNisn: '2530311086',
    nama: 'SUFYAN TSAURY',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Perpanjangan',
    fakultas: 'FASYA',
    jurusan: 'HUKUM KELUARGA ISLAM',
    noWa: '081234567890',
    namaWali: 'H. Sutisna',
    noWaWali: '081298765432',
    isInternasional: false,
    pasFotoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    kamarId: 'K-413',
    nomorKamar: '413',
    lantai: 4,
    jajaran: 'BELAKANG',
    bedNumber: 1,
    statusCheckIn: 'CHECKED_IN',
    checkInTimestamp: '2026-08-19T08:30:00Z',
    checkedInBy: 'Ustadz Ridwan (Pengurus Lt.4)',
    catatanBarang: 'Barang aman sesuai ketentuan Ma\'had.',
    qrToken: 'QR-MAHAD-2530311086-413-1',
    registeredAt: '2026-08-15T08:30:00Z',
  },
  {
    id: 'MHS-002',
    nimNisn: '0067999651',
    nama: 'Abdullah Al Mu\'izi Mafas',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Calon Mahasantri Baru',
    fakultas: 'FASYA',
    jurusan: 'HUKUM KELUARGA ISLAM',
    noWa: '085712345678',
    namaWali: 'Drs. H. Mahrus',
    noWaWali: '085787654321',
    isInternasional: false,
    pasFotoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    kamarId: 'K-513',
    nomorKamar: '513',
    lantai: 5,
    jajaran: 'BELAKANG',
    bedNumber: 2,
    statusCheckIn: 'REGISTERED',
    qrToken: 'QR-MAHAD-0067999651-513-2',
    registeredAt: '2026-08-16T14:20:00Z',
  },
  {
    id: 'MHS-003',
    nimNisn: 'INT-PH-846',
    nama: 'Aleanor L. Sharif',
    jenisKelamin: 'L',
    jenisPendaftaran: 'Mahasantri Internasional',
    asalNegara: 'Filipina',
    fakultas: 'FITK',
    jurusan: 'PAI',
    noWa: '+63912345678',
    namaWali: 'Sharif Family',
    noWaWali: '+63998765432',
    isInternasional: true,
    pasFotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    kamarId: 'K-209',
    nomorKamar: '209',
    lantai: 2,
    jajaran: 'DEPAN',
    bedNumber: 1,
    statusCheckIn: 'REGISTERED',
    qrToken: 'QR-MAHAD-INT-PH-846-209-1',
    registeredAt: '2026-08-17T09:00:00Z',
  }
];

export const FAKULTAS_LIST = [
  'FITK (Fakultas Ilmu Tarbiyah & Keguruan)',
  'FASYA (Fakultas Syariah & Hukum)',
  'FEBI (Fakultas Ekonomi & Bisnis Islam)',
  'FDKI (Fakultas Dakwah & Komunikasi Islam)',
  'FUA (Fakultas Ushuluddin & Adab)',
];

export const ATURAN_BARANG = [
  { item: 'Pemanas Air / Dispenser Listrik / Setrika', allowed: false, desc: 'Dilarang (Bervoltase besar)' },
  { item: 'Rice Cooker / Magic Com', allowed: false, desc: 'Dilarang di kamar (Kecuali di dapur umum)' },
  { item: 'Kompor Gas Portable / Spiritus', allowed: false, desc: 'Sangat dilarang demi keselamatan' },
  { item: 'Rokok / Vape / E-Cigarette / Narkoba', allowed: false, desc: 'Kawasan Bebas Asap Rokok 100%' },
  { item: 'Handphone, Laptop, Tablet, Powerbank', allowed: true, desc: 'Diizinkan untuk perkuliahan' },
  { item: 'Perlengkapan Sholat & Mushaf Al-Qur\'an', allowed: true, desc: 'Wajib dibawa' },
  { item: 'Peralatan Mandi & Cuci Pakaian', allowed: true, desc: 'Ember, gayung, hanger, dll.' },
  { item: 'Obat-obatan Pribadi', allowed: true, desc: 'Wajib lapor jika ada riwayat sakit khusus' },
];

export const DEFAULT_ADMIN = {
  email: 'admin@mahad.uinssc.ac.id',
  nama: 'Superadmin UPT Ma\'had',
  password: 'adminmahad2026',
  role: 'ADMIN' as const,
};

export const DEFAULT_PENGURUS_LIST = [
  {
    id: 'PGR-LT1',
    username: 'pengurus.lt1',
    nama: 'Ustadz Hasan (Pengurus Lantai 1)',
    lantai: 1,
    gedung: "Ma'had Qodim",
    password: 'mahad2026',
    noWa: '08123456701',
  },
  {
    id: 'PGR-LT2',
    username: 'pengurus.lt2',
    nama: 'Ustadz Farhan (Pengurus Lantai 2 - Internasional)',
    lantai: 2,
    gedung: "Ma'had Qodim",
    password: 'mahad2026',
    noWa: '08123456702',
  },
  {
    id: 'PGR-LT3',
    username: 'pengurus.lt3',
    nama: 'Ustadz Ridwan (Pengurus Lantai 3)',
    lantai: 3,
    gedung: "Ma'had Qodim",
    password: 'mahad2026',
    noWa: '08123456703',
  },
  {
    id: 'PGR-LT4',
    username: 'pengurus.lt4',
    nama: 'Ustadz Zaky (Pengurus Lantai 4)',
    lantai: 4,
    gedung: "Ma'had Qodim",
    password: 'mahad2026',
    noWa: '08123456704',
  },
  {
    id: 'PGR-LT5',
    username: 'pengurus.lt5',
    nama: 'Ustadz Muhsin (Pengurus Lantai 5)',
    lantai: 5,
    gedung: "Ma'had Qodim",
    password: 'mahad2026',
    noWa: '08123456705',
  },
];

